info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

security:
  user:
    name: admin
    password: admin

omnius-watcheye:
  collectorsPoolSize: 5
